name: CI Workflow

on:
  pull_request:
    branches:
      - tmp/202*
permissions: write-all
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: echo "something1"
        # Simulating a scheduled cron workflow or  a workflow with secrets run by a user by triggering this run

      - name: Run tests
        run: npm test
